<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>PoEToolbox.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PoEToolbox.Sdk\PoEToolbox.Sdk.csproj" />
    <ProjectReference Include="..\LibBundledGGPK3\LibBundledGGPK3.csproj" />
  </ItemGroup>

</Project>
