<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>PoEToolbox.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PoEToolbox.Sdk\PoEToolbox.Sdk.csproj" />
    <ProjectReference Include="..\LibBundledGGPK3\LibBundledGGPK3.csproj" />
    <ProjectReference Include="..\LibDat2\LibDat2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PoEToolbox.Tests" />
    <InternalsVisibleTo Include="PoEToolbox.Plugins.FxPatch" />
    <InternalsVisibleTo Include="PoEToolbox.Plugins.AffixWorkbench" />
    <InternalsVisibleTo Include="PoEToolbox.App" />
    <InternalsVisibleTo Include="PoEToolbox" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Patches\**\*.patch.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
