<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Description>Library for Content.ggpk of game PathOfExile (Rewrite of LibGGPK2)</Description>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<InvariantGlobalization>true</InvariantGlobalization>
		<IsAotCompatible>true</IsAotCompatible>
		<RollForward>LatestMajor</RollForward>
		<NoWarn>1573;1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="aianlinb.SystemExtensions" Version="1.8.0" />
	</ItemGroup>

</Project>
